"""Objects package for object-centric ARC reasoning."""

from src.objects.dsl import (
    count_objects,
    extract_object,
    filter_by_area,
    filter_by_color,
    filter_by_position,
    filter_by_shape,
    filter_by_size,
    recolor_object,
    recolor_objects,
    render_objects,
    select_adjacent,
    select_contained,
    select_largest,
    select_matching,
    select_smallest,
    select_unique,
    sort_by_area,
    sort_by_position,
    translate_object,
    translate_objects,
)
from src.objects.graph import ObjectEdge, ObjectGraph, ObjectNode
from src.objects.relations import (
    above,
    adjacent_to,
    below,
    compute_all_pairwise_relations,
    contains,
    distance_between,
    horizontally_aligned,
    inside,
    left_of,
    nearest_to,
    overlaps,
    right_of,
    same_color,
    same_shape_signature,
    same_size,
    symmetric_with,
    touching,
    vertically_aligned,
)
from src.objects.segmentation import (
    ObjectInstance,
    SegmentationHypothesis,
    SegmentationStrategy,
    detect_background,
    label_components,
    make_object,
    segment_grid,
    segment_grid_multi,
)

__all__ = [
    # Segmentation
    "ObjectInstance",
    "SegmentationStrategy",
    "SegmentationHypothesis",
    "detect_background",
    "label_components",
    "make_object",
    "segment_grid",
    "segment_grid_multi",
    # Relations
    "adjacent_to",
    "touching",
    "overlaps",
    "contains",
    "inside",
    "left_of",
    "right_of",
    "above",
    "below",
    "horizontally_aligned",
    "vertically_aligned",
    "same_color",
    "same_shape_signature",
    "same_size",
    "distance_between",
    "nearest_to",
    "symmetric_with",
    "compute_all_pairwise_relations",
    # Graph
    "ObjectNode",
    "ObjectEdge",
    "ObjectGraph",
    # DSL
    "filter_by_color",
    "filter_by_area",
    "filter_by_size",
    "filter_by_position",
    "filter_by_shape",
    "sort_by_area",
    "sort_by_position",
    "select_largest",
    "select_smallest",
    "select_unique",
    "select_matching",
    "select_adjacent",
    "select_contained",
    "count_objects",
    "recolor_object",
    "recolor_objects",
    "translate_object",
    "translate_objects",
    "extract_object",
    "render_objects",
]
